Item Type Endpoints
hsse-tech/hsse-tech-backend pull request #12
Opened 2024-03-23 20:16 UTC by FismanMaxim

Написал контроллер, сервисы, репозитории и т.д. для эндпойнтов, связанных с предметами и их типами (Item, ItemType). 

Написал на все тесты.

Для ItemType -- готовы все эндпойнты.
Для Item - готовы все эндпойнты, кроме единственного:

> GET /api/renting/items/{id}?loadRentInfo={bool} - получает информацию об определенном предмете. Если указан параметр в запросе loadRentInfo=true, тогда необходимо вернуть массив всех броней на будущее.

2024-03-23 21:19 UTC, DenVot requested changes

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemController.java
> +  public void createItem(@PathVariable("itemId") UUID itemId) {
Опечатка

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemController.java
>  @RequestMapping("/api/renting")
Валидация отключена

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemTypeController.java
> +public class ItemTypeController {
Валидация отключена

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/RentController.java
>    public void requestOpenItem(@PathVariable("id") long itemId) {}
Лучше кинуть `UnsupportedOperationException`

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/CreateItemRequest.java
> +  public Item getItem() {
Не совсем очевидно что делает этот метод. Кажется, что он что-то должен получать. Лучше его назвать назвать как-нибудь `extractItemDbEntity`

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/CreateItemTypeRequest.java
> +  public ItemType getItemType() {
Аналогично к `CreateItemRequest`

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeService.java
> +public class ItemTypeService {
Есть ощущение, что чисто функционально `ItemTypeService` и `ItemService` можно слить, потому что они в принципе отвечают за одну и ту же проблемную область.

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeService.java
> +
Все ифы прям длинные, мне кажется, что лучше их не писать в одну линию и обернуть их в фигурные скобки

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeService.java
> +  public void updateItemType(UUID itemTypeId, UpdateItemTypeRequest request) {
Мне вообще не особо нравится, что мы в аргументы сервисов принимаем объекты запросов. Задаешь сразу же себе вопрос: "а что если мы захотим использовать этот метод вне контроллера? То есть у нас существуют HTTP запросы, которые на самом деле не HTTP запросы?". Будет логичнее переименовать тип в какое-нибудь другое имя, не завязанное на Request, например, `ItemTypeDelta`.

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeService.java
> +  public ItemType createItemType(CreateItemTypeRequest request) {
Аналогично с `updateItemType`, более осмысленное название для класса, которое не завязано на HTTP

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemService.java
> +  public void updateItem(UUID itemId, UpdateItemRequest request) {
Аналогично с `ItemTypeService.updateItemType`, более осмысленное название для класса, которое не завязано на HTTP

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemService.java
> +  public Item createItem(CreateItemRequest request) {
Аналогично с `ItemTypeService.updateItemType`, более осмысленное название для класса, которое не завязано на HTTP

2024-03-23 21:19 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/data/repositories/JpaRentRepositoryTest.java
> +  // region Test objects
Закос под C# зачет

2024-03-23 21:19 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/ItemServiceTest.java
> +  void testCreateItem() {
А если такого типа предмета не существует?

2024-03-23 21:19 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/CreateItemRequest.java
> +public record CreateItemRequest(String displayName, ItemType itemType) {
Такс. А что у нас делают объекты базы данных в запросах к API? Их вообще можно десериализовать?

2024-03-23 21:19 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/ItemServiceTest.java
> +    var createItemRequest = new CreateItemRequest(itemName, itemType);
А как нам клиент передаст тип предмета, как объект базы данных?

2024-03-23 21:19 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/ItemServiceTest.java
> +  void updateItem() {
А если мы обновляем предмет, которого не существует?

2024-03-23 21:19 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeServiceTest.java
> +  void testUpdateItemType() {
А что если мы пытаемся обновить тип, которого не существует?

2024-03-24 12:34 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemController.java
> +  public void createItem(@PathVariable("itemId") UUID itemId) {
@DenVot  Не понял

2024-03-24 12:35 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemController.java
>  @RequestMapping("/api/renting")
@DenVot  Не понял

2024-03-24 12:35 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemTypeController.java
> +public class ItemTypeController {
@DenVot Не понял

2024-03-24 12:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/CreateItemRequest.java
> +  public Item getItem() {
`extractItemDbEntity` - но он не извлекает айтем из базы данных.

2024-03-24 12:42 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeService.java
> +public class ItemTypeService {
Я их специально разлил, как раз потому, что они отвечают все-таки за разные вещи. Их можно было бы слить, если бы количество методов было таким, каким оно было в твоей фигме. Но  добавил апдейт и удаление и айтемов, и типов. Под single responsibility много чего можно подогнать, но смысла в этом я не вижу, количество классов нам никто не ограничивает

2024-03-24 12:49 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeService.java
> +  public void updateItemType(UUID itemTypeId, UpdateItemTypeRequest request) {
Ну то что эта проблема (хотя я не на 100% согласен, что это проблема) решается переименованием request в delta я не согласен. Request здесь можно воспринимать просто в значении "запрос", а не "http-запрос". Собственно,  так и воспринимаю. Можно вместо объекта request принимать много аргументов, но зачем принимать много аргументов, когда можно принимать мало аргументов в виде dto-шки. Мы их для того и юзаем. 
Можно придираться к кодстайлу, но давай не будем сильно придираться к именам.

2024-03-24 12:51 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/ItemServiceTest.java
> +  void testCreateItem() {
Ну его и не существует. Эта функция проверяет, что он успешно создается.

2024-03-24 13:15 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemController.java
> +  public void createItem(@PathVariable("itemId") UUID itemId) {
А понял

2024-03-24 13:49 UTC, FismanMaxim commented
А я думал, Шувалов делает огромные changes requests...

2024-03-25 12:42 UTC, DenVot requested changes
Ну в общем с кайфом. То где я пометил, что меня не устраивают имена типов, это можно не поправлять

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/ItemType.java
> +  @JsonProperty("max_rent_time_minutes")
Ты хочешь объекты базы данных переводить в JSON? Как будто бы это не лучшая идея

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemController.java
> +    return new ResponseEntity<>(new ClientServerError(e.getMessage()), HttpStatus.NOT_FOUND);
404 NOT FOUND тут некорректен. 404 - код ошибки, когда **станица** не найдена, но если не найден объект базы данных (то есть пользователь ввел по факту некорректные данные), мы возвращаем 403 BAD REQUEST

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemController.java
> +  @PostMapping()
Если ты не предаешь аргументы, то ты можешь указывать атрибут без скобок

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemTypeController.java
> +  @PatchMapping("/{id}")
А ты уверен, что вот такой маппинг будет не `/api/renting/item-type/{id}`, а не `/{id}`?

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/EditRentTimeRequest.java
> +    @JsonProperty("item_") UUID itemId,
Лишнее подчеркивание

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/RentItemRequest.java
> +    @JsonProperty("user_id") UUID userId,
А у нас может быть UUID может быть `null`?

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/responses/GetRentResponse.java
> +public record GetRentResponse(UUID id, User renter, Instant startTime, Instant endTime) {
На сколько я понял, что данная сущность по факту описывает ренту. Тогда логичнее было бы назвать ее `RentApiEntity`

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemService.java
> +    if (itemRepository.findById(itemId).isPresent()) itemRepository.deleteById(itemId);
Есть функция `existsById`, что позволяет не подгружать данные сущности из БД

2024-03-25 12:42 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemTypeService.java
> +  public void updateItemType(UUID itemTypeId, UpdateItemTypeRequest request) {
Ок

2024-03-25 14:33 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/ItemType.java
> +  @JsonProperty("max_rent_time_minutes")
В одном эндпойнте нам нужно вернуть полностью эквивалентный объекты бд. Не вижу смысла создавать DTO, полностью копирующий уже существующий объект. Если потом будет необходимость создам, но в довольно долгосрочной перспективе проблем в этом вроде не вижу...

2024-03-25 14:36 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemTypeController.java
> +  @PatchMapping("/{id}")
Одно из двух "не" явно лишнее:) Не знаю какое, но да, я уверен, что тут все правильно. Если я не прав, в любом случае, когда-нибудь я напишу тесты на контроллеры.

2024-03-26 06:10 UTC, DenVot approved these changes

2024-03-26 10:08 UTC, merged