Rent service
hsse-tech/hsse-tech-backend pull request #19
Opened 2024-04-07 21:31 UTC by FismanMaxim

Написал контроллер и сервис для рент согласно нынешнему состоянию фигмы.

Тесты на сервис, на контроллер пока нет.

В дальнейшем планируется удалить возможность обновлять ренту; возможно, ввести ограничение на максимальное время, за которое до начала ренты можно ее отменить с возвращением денег.

2024-04-08 13:03 UTC, DenVot requested changes
Какая-то непонятка полная с тестами (мб я как-то чето не увидел), но ты почему во всех сьютах, где ты хочешь протестить взаимодействие с БД, ты мокаешь сервис и возвращаешь какие-то значения. Встает вопрос, а зачем тут БД?

2024-04-08 13:03 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/auxiliary/VerificationResult.java
> +public class VerificationResult {
Дак эта же фигня в другом PR...

2024-04-08 13:03 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/ConfirmationPhotoRepositoryOnDrive.java
> +  private static final String BASE_PATH = System.getenv("PHOTO_CONFIRM") + "/";
Переименуй переменную среды на более конкретное `PHOTO_CONFIRMATION_PATH`

2024-04-08 13:03 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/ConfirmationPhotoRepositoryOnDrive.java
> +    Files.write(path, photoBytes);
В целях того, чтобы случайно не затереть уже существующий файл (я не знаю, когда такая ситуация может произойти), лучше поставить настройку записи, чтобы она требовала создания нового файла. Т.е. если файл уже существовал выдавалось исключение

2024-04-08 13:03 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/CreateRentRequest.java
>      @JsonProperty("user_id") @NotNull UUID userId,
Немного про недалекое будущее. У нас заранее будет известен ID пользователя вне `CreateRentRequest`. Поэтому морально приготовься, что вот эту хрень придется удалить (ну а чтобы это было быстрее надо заставить Диму сделать быстрее авторизацию)

2024-04-08 13:03 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemControllerTest.java
> -    GetRentResponse retrievedRent = response.getRents().get(0);
Я вот сейчас заметил такую вещь. А, собственно, зачем ты в тестах используешь БД, если по факту ты мокаешь сервис, а БД не используешь?

2024-04-08 13:03 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/rentservice/ConfirmRentFinishTest.java
> +class ConfirmRentFinishTest extends DatabaseSuite {
Такой же рофл. Зачем ты используешь БД, если ты не все мокаешь?

2024-04-08 16:02 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/auxiliary/VerificationResult.java
> +public class VerificationResult {
Ну я делал другой, а потом подумал, что будет удобно ее запихнуть в процессинг ренты, и в другой ветке все сделал, чтобы тебе по быстрому залить, чтобы тебе не пришлось сильно переписывать свои сервисы. 
Видишь как я о тебе забочусь)

2024-04-08 16:08 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/CreateRentRequest.java
>      @JsonProperty("user_id") @NotNull UUID userId,
Эх грусть печаль тоска досада

2024-04-08 17:47 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/ConfirmationPhotoRepositoryOnDrive.java
> +  private static final String BASE_PATH = System.getenv("PHOTO_CONFIRM") + "/";
Fixed

2024-04-14 17:07 UTC, DenVot approved these changes

2024-04-14 17:07 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/ConfirmationPhotoRepositoryOnDrive.java
> +public class ConfirmationPhotoRepositoryOnDrive implements ConfirmationPhotoRepository {
_Не все то, что репозиторий, то репозиторий_

Конфуций

2024-04-14 17:55 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/ConfirmationPhotoRepositoryOnDrive.java
> +public class ConfirmationPhotoRepositoryOnDrive implements ConfirmationPhotoRepository {
@DenVot Учитывая, что на jpa репозиториях можно не вешать @Repository, то это работает и в обратную сторону

2024-04-14 17:55 UTC, merged