Создание пайплана оплаты
hsse-tech/hsse-tech-backend pull request #20
Opened 2024-04-08 21:54 UTC by DenVot

Список изменений:
- Добавлены `PaymentCreateRentProcessor` и `PaymentDeleteRentProcessor`
- Пофикшена схема БД (теперь транзакции могут быть отрицательными)
- Пофикшены тесты

2024-04-09 14:57 UTC, FismanMaxim requested changes
Нехороший человек, изменил с таким трепетом написанные мною тесты.

Мне кажется, вместо WalletNotFoundException стоит использовать EntityNotFoundException. Подробнее - в комментах. 
Если так, то EntityNotFoundException стоит вынести из RentService'а в папку exceptions более высокого уровня.

2024-04-09 14:57 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/HumanUserPassport.java
> +  private Wallet wallet;
Я придираюсь к уже залитому коду, но все же, почему нигде нет валидирующих аннотаций? Я же, скорее всего, использую в своем коде @Valid HumanUserPassport, а в нем, оказывается, никакой валидации по факту нет.

Ну хотя бы @NotBlank на строки, @NotNull на юзер и кошелек, @Email на email. Плюс хорошо бы убрать сеттер айди (типа @Setter(access = NONE)).

То же для других энтитей.

2024-04-09 14:57 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/RentCostCalculator.java
> +    var rentTimeHour = (to.getEpochSecond() - from.getEpochSecond()) / HOUR_SECONDS;
Я почти написал, что для любой продолжительности меньше часа, rentTimeHour=0, пока не заметил, что HOUR_SECONDS это float, а не int.

Вот бы это было появнее)

2024-04-09 14:57 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/RentCostCalculator.java
> +    var rentTimeHour = (to.getEpochSecond() - from.getEpochSecond()) / HOUR_SECONDS;
Кстати неплохо было бы написать тесты на эту функцию

2024-04-09 14:57 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
> +      var trans = transactionService.createTransaction(new TransactionInfo(rentCost, wallet.getId(), transName, Optional.empty()));
А почему описание транзакции пустое? Даже не просто пустое, а пустой Optional.

Может стоит туда запихнуть какую-то полезную инфу? Например инфу о вещи и времени ренты писать в description, а в name просто "Оплата новой аренды"?

2024-04-09 14:57 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentDeleteRentProcessor.java
> +    var transInfo = new TransactionInfo(rentCost, wallet.getId(), transName, Optional.empty());
Тот же вопрос, что при создании ренты: createTransaction может кинуть WalletNotFound

2024-04-09 14:57 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
> +      var trans = transactionService.createTransaction(new TransactionInfo(rentCost, wallet.getId(), transName, Optional.empty()));
createTransaction может кинуть WalletNotFoundException, а здесь он никак не ловится. При этом RentService, запуская processCreate, не ожидает, что он выбросит ошибку. Если createTransaction выбросит WalletNotFoundException, то этот процессор перебросит ее в сервис, а тот в контроллер. А на контроллере нет ExceptionHandler'а для WalletNotFoundException и будет 500 INTERNAL ERROR. 

Думаю, нужно либо добавить обработку и возвращать buildInvalid, либо вместо WalletNotFoundException кидать EntityNotFoundException. 

Но лучше первый вариант, а WalletNotFoundException, мне кажется, вообще стоит удалить. В EntityNotFoundException есть [конструктор](https://github.com/hsse-tech/hsse-tech-backend/blob/75fcd925bec35ce0c4dffab64e69c8527d77618f/src/main/java/com/mipt/hsse/hssetechbackend/rent/exceptions/EntityNotFoundException.java#L15), принимающий тип энтити и айди, по которому его пытались найти.

2024-04-09 14:57 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentDeleteRentProcessor.java
> +    var targetTrans = transactionService.createTransaction(transInfo);
_Вообще, мне не нравится, что создание транзакций оплаты и возврата выполняется одной функцией, просто с отрицательным аргументов, но вроде ошибок нет_

2024-04-09 14:57 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/BigDecimalHelper.java
> +    Assertions.assertEquals(0, actual.compareTo(expected));
_`Assertions.` можно было и не писать, но ладно_

2024-04-09 14:57 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/data/repositories/JpaRentRepositoryTest.java
> +    userRepository.save(user);
Я не против, но почему?

2024-04-09 14:57 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/payments/rent/CreatingRentTests.java
> +public class CreatingRentTests extends DatabaseSuite {
Было бы очень хорошо, если бы ты переименовал это. 
Потому что под именем CreateRestTest у меня в соседнем PR написаны тесты на сервис рент (без кошелька). Это, конечно, другая папка, но плохо, что названия почти одинаковые (а по смыслу так полностью одинаковые).

_CreateTransactionOnRentCreationTest_?

2024-04-09 14:57 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/payments/services/TransactionServiceCreatingTransactionTest.java
> +    var transactionInfo = new TransactionInfo(BigDecimal.valueOf(50.00), testWallet.getId(), "Гель для душа", Optional.of("О полмолив, мой нежный гель"));
Зачет)))

2024-04-09 14:57 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemControllerTest.java
> +    jpaHumanUserPassportRepository.deleteAll();
Раз уж ты перенес все в BeforeEach, то можно удалить эти строки из теста getItemWithFutureRents().

+ добавить сюда userRepository.deleteAll()

(стр. 165)

2024-04-11 20:25 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/RentCostCalculator.java
> +    var rentTimeHour = (to.getEpochSecond() - from.getEpochSecond()) / HOUR_SECONDS;
> Кстати неплохо было бы написать тесты на эту функцию
Соглашусь, но эта функция была получена как побочка рефакторинга после цикла TDD, поэтому по факту можно и не писать 👀

2024-04-11 20:26 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
> +      var trans = transactionService.createTransaction(new TransactionInfo(rentCost, wallet.getId(), transName, Optional.empty()));
Ну да, соглашусь это было бы более информативно

2024-04-11 20:28 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentDeleteRentProcessor.java
> +    var targetTrans = transactionService.createTransaction(transInfo);
Но а как ты хочешь?

2024-04-11 20:29 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/BigDecimalHelper.java
> +    Assertions.assertEquals(0, actual.compareTo(expected));
Это идейка виновата, она не удалила 😭

2024-04-11 20:30 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/data/repositories/JpaRentRepositoryTest.java
> +    userRepository.save(user);
В силу нашей хреновой архитектуры тестирования, у нас ко времени выполнения `JpaRentRepositoryTest` может прийти БД, которая заполнена неожиданными данными, которые ломают тест

2024-04-11 20:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentDeleteRentProcessor.java
> +    var targetTrans = transactionService.createTransaction(transInfo);
Ну в двух функциях обрабатывать. Там просто у тебя есть проверка, что (кол-во денег - сумма транзакции) > 0, а если сумма транзакции меньше 0, то это уже какое-то вырожденное условие получается. Мне это эстетически не понравилось.

2024-04-14 17:09 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/HumanUserPassport.java
> +  private Wallet wallet;
NotNull иногда ломает логику программы и кидает исключения, когда не нужно. Потому что на значения по умолчанию ему пофек и он все равно выкидывает ошибку

2024-04-14 17:10 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
> +      var trans = transactionService.createTransaction(new TransactionInfo(rentCost, wallet.getId(), transName, Optional.empty()));
Да-да я учту, забыл про него

2024-04-14 17:11 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/payments/rent/CreatingRentTests.java
> +public class CreatingRentTests extends DatabaseSuite {
payments.rent!!!!!!! Но пусть будет по твоему

2024-04-14 17:59 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/HumanUserPassport.java
> +  private Wallet wallet;
@DenVot Хмм, можно источник этого утверждения?

2024-04-14 18:01 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/HumanUserPassport.java
> +  private Wallet wallet;
А другие аннотации все равно хорошо бы

2024-04-14 18:01 UTC, FismanMaxim commented
Опа конфликтики, прикольно)

2024-04-14 18:35 UTC, DenVot commented
ТЫ СВОИМ АВТОФОРМАТИРОВАНИЕМ ДДЛ МНЕ ПОЛТЕСТОВ СЛОМАЛ!!!!!!!

2024-04-14 18:51 UTC, FismanMaxim approved these changes

2024-04-14 18:51 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
> +    } catch (WalletNotFoundException e) {
Я так понимаю, есть причина, по которой ты не хочешь отказываться от WallterNotFoundException  в пользу EntityNotFoundException?

2024-04-14 18:56 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
> +    } catch (WalletNotFoundException e) {
Я хочу по итогу сделать его наследуемым от EntityNotFoundException, чтобы сделать Global Exception Handler, на это исключения, но это мы позже обсудим

2024-04-14 18:56 UTC, merged