Rent controller
hsse-tech/hsse-tech-backend pull request #21
Opened 2024-04-14 21:08 UTC by FismanMaxim

2024-04-15 21:04 UTC, DenVot requested changes

2024-04-15 21:04 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemControllerTest.java
> +    itemTypeRepository.deleteAll();
Напоминаю, что мы обратно перешли к концепции @BeforeEach/@AfterEach

2024-04-15 21:04 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemControllerTest.java
> +    itemTypeRepository.deleteAll();
И у меня такой же вопрос остается. Зачем мы юзаем DatabaseSuite, если БД мы не используем по факту... Я тут нашел аннотацию [`@WebMvcTest`](https://spring.io/guides/gs/testing-web), это должно решить проблему.

2024-04-15 21:04 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/RentControllerTest.java
> +class RentControllerTest extends DatabaseSuite {
Аналогично, попробуй `@WebMvcTest`

2024-04-15 21:04 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/rentservice/UpdateRentTest.java
> +    rentRepository.deleteAll();
Перемести в `clear()`

2024-04-15 21:04 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/services/rentservice/UpdateRentTest.java
> +  private boolean equalsInstantsWithDelta(Instant a, Instant b) {
Я думаю, что для удобства можно перевести в отдельный класс со статическим методом, потому что не только в этом тесте (и не только тебе) может понадобиться такая удобная вещь

2024-04-15 21:04 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/RentService.java
> +  // endregion
мы не в сишарпе((( тут нет регионов

2024-04-16 19:34 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemControllerTest.java
> +    itemTypeRepository.deleteAll();
Нас колышет как будто шторм 10 баллов

2024-04-16 20:09 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemControllerTest.java
> +    itemTypeRepository.deleteAll();
Да, оно работает. В другой ветке использую ее потом.

2024-04-16 20:47 UTC, DenVot approved these changes

2024-04-16 21:42 UTC, merged