Tests to mock mvc
hsse-tech/hsse-tech-backend pull request #26
Opened 2024-04-17 18:49 UTC by FismanMaxim

2024-04-17 18:59 UTC, FismanMaxim commented
Congratulations, my little friends!
We have successfully reached the milestone of 100 tests!

Cheers! 🥂🥂🥂

![image](https://github.com/hsse-tech/hsse-tech-backend/assets/53466104/b2fdd7cd-566c-4293-a4f9-83000a37b449)

2024-04-18 09:48 UTC, DenVot requested changes
Меня напрягает, что ты фотку как-то в жсон пытаешься пихнуть

2024-04-18 09:48 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/ItemType.java
> +  @JsonIgnore
Почему мы игнорим это?

2024-04-18 09:48 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/PinPhotoConfirmationRequest.java
> +public record PinPhotoConfirmationRequest(@JsonProperty("photo") BytesArray photoBytesArray) {}
Эм. А как ты собираешься брать поток байтов из джсона. Мы вроде договаривались использовать octet-stream использовать

2024-04-18 09:48 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/responses/CreateRentResponse.java
>    private final String errorMessage;
Зачем?

2024-04-18 09:48 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/RentService.java
> +        return new BytesArray(photoBytes);
Наверное было было бы неплохо знать тип файла

2024-04-18 15:55 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/ItemType.java
> +  @JsonIgnore
Объяснил

2024-04-18 15:56 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/requests/PinPhotoConfirmationRequest.java
> +public record PinPhotoConfirmationRequest(@JsonProperty("photo") BytesArray photoBytesArray) {}
Блин че ты сразу не сказал какая удобная штука этот octet-stream

2024-04-18 17:09 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/controllers/responses/CreateRentResponse.java
>    private final String errorMessage;
Сделал крутой ExceptionHandling

2024-04-19 09:50 UTC, DenVot approved these changes
Вообще я наблюдаю тендецию превращения ItemService в божественный класс и уже нарушается SRP. В будущем стоит задуматься о его декомпозиции на более мелкие классы. Ну а так все норм

2024-04-19 09:50 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/apierrorhandling/RestExceptionHandler.java
> +    return new ResponseEntity<>(apiError, apiError.getStatus());
Респект. Это выглядит прекрасно

2024-04-29 14:09 UTC, merged