Added pinning and getting thumbnail photo of an item
hsse-tech/hsse-tech-backend pull request #30
Opened 2024-05-09 04:18 UTC by FismanMaxim

2024-05-11 22:53 UTC, DenVot requested changes
Меня напрягает один момент, который я тебе описал

2024-05-11 22:53 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/photorepository/PhotoRepositoryOnDrive.java
> +      PhotoType.RENT_CONFIRMATION, "rent_confirmation",
А не лучше ли было сделать класс, где у тебя будут висеть константы `RENT_CONFIRMATION` и `ITEM_THUMBNAIL` в строковом виде? Например, так:
```java
public static final String RENT_CONFIRMATION = "rent_confirmation";
```

2024-05-12 06:33 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/photorepository/PhotoRepositoryOnDrive.java
> +      PhotoType.RENT_CONFIRMATION, "rent_confirmation",
Я пофиксил, но не так как ты предложил. Не знаю насколько это хороший кодстайл, но выглядит красиво

2024-05-17 09:14 UTC, DenVot approved these changes

2024-05-17 09:14 UTC, merged