OAuth 2.0
hsse-tech/hsse-tech-backend pull request #43
Opened 2024-06-25 15:09 UTC by DenVot

Описание изменений написаны в issue прикрепленном к PR
- #41

2024-06-25 19:59 UTC, FismanMaxim requested changes

2024-06-25 19:59 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/User.java
> -  private String userType;
Кста, userType у нас это вроде замок/человек.
А почему это не enum? Мы же вроде давно научились сохранять enum'ы в бд

2024-06-25 19:59 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/oauth/PhystechDomainValidator.java
> +        return countMatched == PHYSTECH_DOMAIN.length() && i == email.length();
Я, честно говоря, вообще не понимаю, зачем все эти 30 строк.

Почему нельзя написать в одну строку `return email.endsWith(PHYTECH_DOMAIN);` (где `PHYSTECH_DOMAIN="@phystech.edu"`). Мы ж верим, что приходит валидный email

(Это вообще работает за O(1))

2024-06-25 19:59 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/users/administation/README.md
> +[WARN] Super administrator not found. Activation key: 8755d631-0186-42ef-a82f-63501453808b
Это же не реальный ключ. Может написать плейсхолдер (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx), а не какой-то рандомный ключ, который ничего не значит?

2024-06-25 19:59 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/users/administation/UserService.java
> +        var user = passportRepository.findById(userId).orElseThrow(EntityNotFoundException::new);
Ну, вообще, когда я создавал EntityNotFoundException, я не предполагал его использование без типа энтити.
Хотя наверно в таком случае мне не следовало создавать конструктор без аргументов...

2024-06-25 19:59 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/oauth/PystechDomainValidatorTest.java
> +    assertFalse(PhystechDomainValidator.isValid("furmanov.maoutlook.com"));
Если придираться, то в доке функции isValid было написано, что входящий email соответствует regex'у email'а. Я так понимаю, имеется в виду грубо говоря "\*@\*.\*".
А тут собаки нет, так что это нерепрезентативный тест и, вообще говоря, функция имеет право вести себя как угодно на этой строке

2024-06-25 19:59 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/oauth/PystechDomainValidatorTest.java
> +    assertFalse(PhystechDomainValidator.isValid("furmanov.ma@outlook.com"));
Пойду-ка спрошу Михаила, предлагалось ли ему подписать согласие на обработку его персональных данных, оставленных в коде

2024-06-25 19:59 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/oauth/PystechDomainValidatorTest.java
> +    assertFalse(PhystechDomainValidator.isValid("furmanov.ma@outlook.com"));
Сбор, запись, накопление, хранение 🤔

2024-06-25 19:59 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/rent/controllers/ItemControllerTest.java
> +  void setup() {
Не понял, чем тебе не понравилось название, но ладно

2024-06-25 20:01 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/oauth/PhystechDomainValidator.java
> +        return countMatched == PHYSTECH_DOMAIN.length() && i == email.length();
(Особенно если мы верим, что к нам приходит валидный email)

2024-06-25 20:16 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/User.java
> -  private String userType;
А тебе минусик ничего не говорит? Возможно юзера больше нет 😱

2024-06-25 20:17 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/oauth/PhystechDomainValidator.java
> +        return countMatched == PHYSTECH_DOMAIN.length() && i == email.length();
А, да, факт
PS: но это не O(1)

2024-06-25 20:17 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/users/administation/README.md
> +[WARN] Super administrator not found. Activation key: 8755d631-0186-42ef-a82f-63501453808b
Это пример

2024-06-25 20:18 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/oauth/PystechDomainValidatorTest.java
> +    assertFalse(PhystechDomainValidator.isValid("furmanov.maoutlook.com"));
Это придирка

2024-06-25 20:18 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/oauth/PystechDomainValidatorTest.java
> +    assertFalse(PhystechDomainValidator.isValid("furmanov.ma@outlook.com"));
Осуждаю

2024-06-25 21:18 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/oauth/PystechDomainValidatorTest.java
> +    assertFalse(PhystechDomainValidator.isValid("furmanov.maoutlook.com"));
@DenVot Неправда, это нарушение контракта. Ужас-ужас

2024-06-25 21:18 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/User.java
> -  private String userType;
@DenVot А... Действительно...

2024-06-26 11:14 UTC, FismanMaxim approved these changes

2024-06-26 11:15 UTC, merged