Конкретизация EntityNotFoundException и оптимизация проверки суффикса почты
hsse-tech/hsse-tech-backend pull request #49
Opened 2024-06-27 12:13 UTC by DenVot

2024-06-27 19:39 UTC, FismanMaxim requested changes
Все придирки, кроме последнего

2024-06-27 19:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/RublesToKopeckConverter.java
> +  private RublesToKopeckConverter() {}
@NoArgsConstructor(access = PRIVATE) :)

2024-06-27 19:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/RublesToKopeckConverter.java
>  public class RublesToKopeckConverter {
Хех, а что вообще у нас вспомогательный класс делает в корневой папке проекта один на один с классом ApplicationMain?! Вроде у нас есть папка auxiliary

2024-06-27 19:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/apierrorhandling/EntityNotFoundException.java
> +  public static EntityNotFoundException userNotFound(UUID id) {
Ну я не уверен, что это нужно... По отдельному методы на каждую сущность если делать, то тут будет штук 20 методов... Но ладно...

2024-06-27 19:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/oauth/PhystechDomainValidator.java
> -public class PhystechDomainValidator {
Ну в принципе класс можно было и не удалять, чтобы не вызывать везде endsWith ручками

2024-06-27 19:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/oauth/services/OAuth2UserHelper.java
> +  private OAuth2UserHelper() {}
Ну lombok жееееее

2024-06-27 19:39 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
>        return VerificationResult.buildInvalid("Wallet not found");
А вот тут серьезно, это же неправда вроде. 
EntityNotFound может быть выброшен методом commitTransaction выше, если **транзакция** не найдена, а ты обрабатываешь, как будто кошелек не найден. Тогда уж лучше buildInvalid(e.type + " not found") и сохранить тип в исключении (это кстати логично)

2024-06-28 14:02 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/apierrorhandling/EntityNotFoundException.java
> +  public static EntityNotFoundException userNotFound(UUID id) {
Если что, в orElseThrow можно лямбду пихать типа `orElseThrow(() -> new EntityNotFoundException(User.class, id))`

2024-06-29 15:21 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/RublesToKopeckConverter.java
>  public class RublesToKopeckConverter {
А какой умный человек придумал называть папку с утилитами `auxiliary`, а не `utils`, как все нормальные люди?

2024-06-29 15:22 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/apierrorhandling/EntityNotFoundException.java
> +  public static EntityNotFoundException userNotFound(UUID id) {
Если что это и пихается в лямбду + я хотел инкапсулировать использование типов. Это называется фабричный метод

2024-06-30 15:03 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/RublesToKopeckConverter.java
>  public class RublesToKopeckConverter {
То что ты так делаешь, не значит, что все должны так делать. Слово "утилита" примерно такое же абстрактное и неговорящее, как auxiliary. Переименуй, если хочешь.

2024-07-01 22:10 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/RublesToKopeckConverter.java
>  public class RublesToKopeckConverter {
Ну вообще, если посмотришь крупные репы, то там как раз такое имя используется

2024-07-01 22:10 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/oauth/PhystechDomainValidator.java
> -public class PhystechDomainValidator {
Ну разница в два символа некритично)

2024-07-01 22:10 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/payments/rent/PaymentCreateRentProcessor.java
>        return VerificationResult.buildInvalid("Wallet not found");
Согласен. Я добавлю тип в класс тогда

2024-07-01 22:12 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/RublesToKopeckConverter.java
> +  private RublesToKopeckConverter() {}
Факт

2024-07-01 22:15 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/oauth/services/OAuth2UserHelper.java
> +  private OAuth2UserHelper() {}
Да-да-да, я уже понял что я клоун и не могу запомнить этот ваш лобок....

2024-07-01 22:24 UTC, DenVot commented
Все, вроде как, твои замечания пофиксил. Еще раз извиняюсь за резкое высказывание, был тяжелый день тогда

2024-07-02 05:08 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/apierrorhandling/EntityNotFoundException.java
> +  public static EntityNotFoundException userNotFound(UUID id) {
@DenVot По-моему, со всем уважением к паттернам, у тебя количество методов с таким подходом будет сопоставимо количеству энтитй (сейчас их мало, но это просто потому что ты не все создал, т.к. тебе не все пригодилось). А это не звучит круто по-моему.

2024-07-02 17:07 UTC, FismanMaxim approved these changes

2024-07-02 17:07 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/apierrorhandling/EntityNotFoundException.java
>    public EntityNotFoundException() {
Кажется этот конструктор надо удалить, либо добавить в него Class<?> type

2024-07-02 20:31 UTC, merged