Locks service
hsse-tech/hsse-tech-backend pull request #51
Opened 2024-06-28 14:12 UTC by FismanMaxim

2024-06-29 15:41 UTC, DenVot requested changes

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/HumanUserPassport.java
> +    return roles.stream().anyMatch(r -> r.getId().equals(role.getId()));
А по имени не проще?

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/JpaRentRepository.java
> +  // TODO: Есть идея хранить время в MSK; возможно, потом этим займусь
Хранить время в MSK - это лажа

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/controllers/LockController.java
> +  public ResponseEntity<Boolean> isLockOpen(@PathVariable("id") UUID lockId) {
Эта вещь работать не будет. У нас замок не авторизуется

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/controllers/responses/CreateLockResponse.java
> +public record CreateLockResponse(@JsonProperty("id") @NotNull UUID id) {}
JsonProperty? Зачем?

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/exceptions/ItemToLockCouplingException.java
> +public class ItemToLockCouplingException extends Exception {
Обычный exception не сделает rollback транзакции

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/services/LockService.java
> +  public void addItemToLock(UUID lockId, UUID itemId) throws ItemToLockCouplingException {
Transactional где?

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/services/LockService.java
> +  public void removeItemFromLock(UUID lockId, UUID itemId) throws ItemToLockCouplingException {
Transactional где?

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/services/LockService.java
> +    Role adminRole = roleRepository.findByName("ADMIN");
Вот я поэтому и говорю, что легче по имени, потому что генерирует меньше запросов (я тоже у себя это пофиксю)

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/services/LockService.java
> +    // A user can open a lock if there is at least 1 iem under this lock, which is now rented by
Англичанин, ты пишешь проект для MIPT, а не для MIT. По-русски комменты. И звучит как-будто тут должен быть много строчный коммент

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/services/LockService.java
> +  private void setLockOpened(UUID lockId, boolean opened) {
Вообще по названию не очевидно, что это делает. `setLockStatus` звучит более очевидно, иначе я подумал, что этот метод всегда открывает дверь

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemService.java
> + LockService lockService) {
LockServiceBase maybe?

2024-06-29 15:41 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemService.java
> +    return rentRepository.findAllFutureRentsOfItem(itemId);
А если мы завтра перейдем на Mongo? JPA репозитории в контроллере очень опасно. Оберни в интерфейсы лучше

2024-06-29 15:41 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/lock/controllers/LockControllerTest.java
> +@Import({ObjectMapper.class, SecurityConfig.class, MiptOAuth2UserService.class})
Ты же ObjectMapper уже в DI влил

2024-06-29 15:41 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/lock/controllers/LockControllerTest.java
> +    attributes.put("sub", "123");
У нас Yandex OAuth, а не Google OAuth, у нас другой аттрибует

2024-06-29 15:41 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/lock/controllers/LockControllerTest.java
> +            Collections.singletonList(new SimpleGrantedAuthority("ROLE_MIPT_USER")),
У замка нет роли вообще никакой

2024-06-29 15:41 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/lock/controllers/LockControllerTest.java
> +                .with(oauth2Login().oauth2User(commonUserPrincipal)))
У замка роли нет

2024-06-29 15:41 UTC, DenVot commented on src/test/java/com/mipt/hsse/hssetechbackend/lock/services/LockServiceTest.java
> +  private JpaRoleRepository roleRepository;
ААААААА, СЕРДЦЕЕЕЕЕЕЕ

2024-06-30 15:06 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/HumanUserPassport.java
> +    return roles.stream().anyMatch(r -> r.getId().equals(role.getId()));
Ты имеешь в виду заменить "getId" на "getName"? Ну вроде ни с какой стороны не проще, еще и длиннее на дважды по 2 символа.

2024-06-30 15:10 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/JpaRentRepository.java
> +  // TODO: Есть идея хранить время в MSK; возможно, потом этим займусь
Лажа - делать необоснованные заявления. 
Наш код с 99%-ой вероятностью не выйдет за пределы общаги (в лучшем/худшем случае за пределы МФТИ), так что вариант как минимум живабелен, хотя и непривлекателен.

2024-06-30 15:17 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/controllers/responses/CreateLockResponse.java
> +public record CreateLockResponse(@JsonProperty("id") @NotNull UUID id) {}
Можешь, пожалуйста, поподробнее писать комментарии, я тебя не понимаю.
У нас во всех реквестах и во всех респонсах прописаны @JsonProperty.

Или ты о том, что конкретно здесь он не нужен, потому что имя переменной совпадает? Если да, то это не первый раз, когда я так делаю, потому что имя json-свойства я беру с твоих схем, а имя переменной придумываю сам, часто меняю на ходу, и чтобы не думать оригинальное ли это имя со схемки или нет, я лично всегда прописываю, + так читабельнее.

2024-06-30 15:26 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/data/entities/HumanUserPassport.java
> +    return roles.stream().anyMatch(r -> r.getId().equals(role.getId()));
Ну так можно будет передать любую строку, даже не являющуюся ролью... Понятно, что он вернет false как и должен, но такое себе.

2024-06-30 15:35 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/lock/services/LockService.java
> +    // A user can open a lock if there is at least 1 iem under this lock, which is now rented by
"Англичанин, ... по-русски комменты" - что за тоталитарный тон, можно как-то поуважительнее?! Ты вроде не Киреков. Я когда ревьюю, всегда стараюсь комменты писать в формате предложений.

Писать комменты на английском так же нормально, как писать код на английском. И я на протяжении всего проекта их на английском и писал, за редким исключением. К тому же это не цитата из Шекспира, а предложение на уровне типа... A2.

Многострочный - ну он был однострочный, это все idea мне отредачила :) Вообще в джавадок вынесу

2024-06-30 15:37 UTC, FismanMaxim commented on src/main/java/com/mipt/hsse/hssetechbackend/rent/services/ItemService.java
> +    return rentRepository.findAllFutureRentsOfItem(itemId);
Так это сервис, а не контроллер...

2024-06-30 16:01 UTC, FismanMaxim commented on src/test/java/com/mipt/hsse/hssetechbackend/lock/services/LockServiceTest.java
> +  private JpaRoleRepository roleRepository;
Я чета долго не понимал о чем ты, но видимо о переносе строки 😆😆😆

2024-07-01 21:59 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/JpaRentRepository.java
> +  // TODO: Есть идея хранить время в MSK; возможно, потом этим займусь
Мало, кто делает время в МСК. Я, например, студент МФТИ сейчас нахожусь, например, дома во Владивостоке. Захотел забросить пылесос на время, когда я приеду (и тут могут возникнуть проблемы). Поэтому лучше хранить все в универсальном формате +0. Не?

2024-07-01 22:00 UTC, DenVot commented on src/main/java/com/mipt/hsse/hssetechbackend/data/repositories/JpaRentRepository.java
> +  // TODO: Есть идея хранить время в MSK; возможно, потом этим займусь
В принципе я согласен, что на данный момент это несущественно, но вот то, что я написал, в принципе имеет право на жизнь

2024-07-02 11:54 UTC, DenVot approved these changes

2024-07-02 12:13 UTC, merged